### ISSUE TITLE
Brilliant work!  

### ISSUE THREAD

**Issue by clort81** [superzazu/pac#1]
I'm poking around with conversion to terminal braille.
A lot of optimization would be needed to get to 30+ fps, mainly implementation of dirty buffers and a faster lookup for proper braille glyphs.
Even at half resolution 112 colums; it still looks pretty good.
![mypacterm](https://user-images.githubusercontent.com/51511737/219243628-94754821-26a4-4237-ab12-e35013d95311.gif)

**Comment by superzazu** [comment]
That's a fun idea ! 👍
